AllCops:
  TargetRubyVersion: 2.3
  DisplayStyleGuide: true
  Exclude:
    - spec/**/*.rb
    - test_rails_app/**/*
    - example_rails_app/**/*

Rails:
  Enabled: true
Rails/FilePath:
  Enabled: false
Rails/SkipsModelValidations:
  Enabled: false

Metrics/LineLength:
  Max: 160
Metrics/CyclomaticComplexity:
  Max: 10
Metrics/PerceivedComplexity:
  Max: 10
Metrics/AbcSize:
  Max: 20
Metrics/MethodLength:
  Max: 20
Metrics/ClassLength:
  Max: 200

Layout/AlignParameters:
  # Alignment of parameters in multi-line method calls.
  #
  # The `with_first_parameter` style aligns the following lines along the same
  # column as the first parameter.
  #
  #     method_call(a,
  #                 b)
  #
  # The `with_fixed_indentation` style aligns the following lines with one
  # level of indentation relative to the start of the line with the method call.
  #
  #     method_call(a,
  #       b)
  EnforcedStyle: with_first_parameter

# Multi-line method chaining should be done with trailing dots.
Layout/DotPosition:
  EnforcedStyle: leading

Style/Documentation:
  Description: 'Document classes and non-namespace modules.'
  Enabled: false
  Exclude:
    - 'spec/**/*'
    - 'test/**/*'

Style/TrailingCommaInArguments:
  # If `comma`, the cop requires a comma after the last argument, but only for
  # parenthesized method calls where each argument is on its own line.
  # If `consistent_comma`, the cop requires a comma after the last argument,
  # for all parenthesized method calls with arguments.
  EnforcedStyleForMultiline: comma

Style/StringLiterals:
  EnforcedStyle: double_quotes
  # If true, strings which span multiple lines using \ for continuation must
  # use the same type of quotes on each line.
  ConsistentQuotesInMultiline: false

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented_relative_to_receiver
Style/TrailingCommaInLiteral:
  Enabled: true
Style/GuardClause:
  Enabled: false
Style/PredicateName:
  Enabled: false
Style/Semicolon:
  Enabled: false
Style/MultilineBlockChain:
  Enabled: false
