require 'active_mocker/collection_association'
require 'active_mocker/mock_class_methods'
require 'active_mocker/mock_instance_methods'
require 'active_hash'
require 'active_hash/ar_api'
require 'active_mocker/class_exists'