source 'https://rubygems.org'

gem 'rails', '4.1'

group :development, :test do
  gem 'sqlite3', '~>1.3'
  gem 'rspec-rails', '~>2'
end

group :test do
  gem 'active_mocker', :path => "../../active_mocker"
  gem 'fuubar'
end
