appraise "rails-4.2" do
  gem "rails", "~> 4.2.8"
  gem "rspec", "~> 3.4"
  gem "rspec-rails", "~>3.4"
end

appraise "rails-5.1" do
  gem "rails",  "~> 5.1.1"
  gem "rspec", "3.5.0"
  gem "rspec-rails", "3.5.0"
end

appraise "rails-5.2" do
  gem "rails",  "~> 5.2.1"
  gem "rspec", "3.7.0"
  gem "rspec-rails", "3.7.0"
end
