# frozen_string_literal: true

source "https://rubygems.org"

gem "appraisal"
gem "rails", "~>4.2"

gem "active_mocker", path: "../"
gem "capybara"
gem "omniauth-identity", "1.1.1"
gem "rspec", ">= 3.4"
gem "sqlite3", "~>1.3.13"
