# frozen_string_literal: true
source "https://rubygems.org"

gem "rails", "~>4.2"
gem "appraisal"

gem "capybara"
gem "rspec", ">= 3.4"
gem "sqlite3", "~>1.3.13"
gem "active_mocker", path: "../"
gem "omniauth-identity", "1.1.1"
