appraise "rails-4.1" do
  gem "rails", "~> 4.1"
  gem "rspec", "~> 3.4"
  gem "rspec-rails", "~>3.4"
end

appraise "rails-4.2" do
  gem "rails", "~> 4.2.7.1"
  gem "rspec", "~> 3.4"
  gem "rspec-rails", "~>3.4"
end

appraise "rails-5.0" do
  gem "rails",  "~> 5.0"
  gem "rspec", "3.5.0"
  gem "rspec-rails", "3.5.0"
end
