source 'https://rubygems.org'

gem 'rails', '4.1.4'
gem 'ruby-prof'

group :development, :test do
  gem 'sqlite3', '~>1.3'
  gem 'rspec-rails', '3'
  gem 'active_mocker', :path => "../../active_mocker"
end

group :test do
  gem 'fuubar', '2.0.0.rc1'
end
